---
- name: Set Ip Loobpack
  hosts: all
  gather_facts: no

  tasks:
    - name: Set loopback IPv4 address
      ios_l3_interface:
            name: loopback {{ item.name }}
            ipv4: "{{ item.ipv4 }}"
      with_items:
           - { name: 1, ipv4: 10.0.1.1/24 }
           - { name: 2, ipv4: 10.0.2.2/24 }
           - { name: 3, ipv4: 10.0.3.3/24 }
           
    - name: Show loopback
      ios_command:
            command:
                - show ip int br
            register: hienhinh

    - debug: var=hienhinh.stdout_lines
    
